services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
        container_name: elastic_search
        environment:
            - node.name=elastic
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata:/usr/share/elasticsearch/data
        ports:
            - 9200:9200

    kibana:
        image: docker.elastic.co/kibana/kibana:7.10.0
        container_name: kibana
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch

    rabbitmq:
        image: rabbitmq:3.13-management
        container_name: rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq

volumes:
    esdata:
        driver: local
    rabbitmq_data:
        driver: local
